sudo: required
services:
    - docker

before_install:
    - docker build -t jvrh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jvrh/react-test npm test

after_success:
    - docker build -t jvrhjvrh/complex-client ./client
    - docker build -t jvrhjvrh/complex-nginx ./nginx
    - docker build -t jvrhjvrh/complex-server ./server
    - docker build -t jvrhjvrh/complex-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jvrhjvrh/complex-client
    - docker push jvrhjvrh/complex-nginx
    - docker push jvrhjvrh/complex-server
    - docker push jvrhjvrh/complex-worker
